---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-application-as
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/ArgoCD-ACM-Refactor/acm-all-managed-cluster-config.git
      revision: v1.0.1
      files:
      - path: "**/cluster.json"
  template:
    metadata:
      name: '{{cluster.name}}-demo-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/ArgoCD-ACM-Refactor/acm-demo-application.git
        targetRevision: main
        path: day2-cluster-config/monitoring/overlays/{{cluster.name}}
      destination:
        server: '{{cluster.address}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
